apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mjcart
data:
  APP_ENV: "production"
  DB_HOST: "mysql"
  REDIS_HOST: "redis"
  AUTH_URL: "http://auth-service:4001"
  USER_URL: "http://user-service:4002"
  PRODUCT_URL: "http://product-service:4003"
  INVENTORY_URL: "http://inventory-service:4004"
  CART_URL: "http://cart-service:4005"
  ORDER_URL: "http://order-service:4006"
  SHIPPING_URL: "http://shipping-service:4007"
  NOTIFICATION_URL: "http://notification-service:4008"
  REVIEW_URL: "http://review-service:4009"
