apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mjcart
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ChangeMe_RootPass123"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "ChangeMe_RootPass123"
  JWT_SECRET: "mjcart-jwt-secret-change-me"
