apiVersion: v1
kind: Secret
metadata:
  name: mjcart-secrets
  namespace: mjcart
type: Opaque
stringData:
  # CHANGE THESE before applying to any real cluster.
  mysql-root-password: "ChangeMe_RootPass123!"
  mysql-user: "root"
  jwt-secret: "ChangeMe_JWTSigningKey_UseSomethingLong"
